name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: https://example.com
          NEXT_PUBLIC_SITE_NAME: "Test Site"
          NEXT_PUBLIC_PHONE: "+33 7 45 04 83 95"
          NEXT_PUBLIC_EMAIL: "test@example.com"
          NEXT_PUBLIC_ADDRESS: "24 avenue des Vosges"
          NEXT_PUBLIC_POSTAL_CODE: "67000"
          NEXT_PUBLIC_CITY: "Strasbourg"
          NEXT_PUBLIC_LAWYER_NAME: "Test Lawyer"
          NEXT_PUBLIC_BAR: "Barreau de Strasbourg"
          NEXT_PUBLIC_SIRET: "12345678900000"
          NEXT_PUBLIC_CALENDLY_URL: "https://calendly.com/test"

      - name: Upload build artifacts
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: .next
          retention-days: 7
