name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_SITE_URL: https://example.com
          NEXT_PUBLIC_SITE_NAME: "Test Site"
          NEXT_PUBLIC_PHONE: "+33 7 45 04 83 95"
          NEXT_PUBLIC_EMAIL: "test@example.com"
          NEXT_PUBLIC_ADDRESS: "24 avenue des Vosges"
          NEXT_PUBLIC_POSTAL_CODE: "67000"
          NEXT_PUBLIC_CITY: "Strasbourg"
          NEXT_PUBLIC_LAWYER_NAME: "Test Lawyer"
          NEXT_PUBLIC_BAR: "Barreau de Strasbourg"
          NEXT_PUBLIC_SIRET: "12345678900000"
          NEXT_PUBLIC_CALENDLY_URL: "https://calendly.com/test"

      - name: Upload build artifacts
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .next
          retention-days: 7

  unit-tests:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit and integration tests
        run: npm run test:run

      - name: Generate coverage report
        if: matrix.node-version == '20.x'
        run: npm run test:coverage

      - name: Upload coverage report
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          retention-days: 7

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_PHONE: "+33 7 45 04 83 95"
          NEXT_PUBLIC_EMAIL: "test@example.com"
          NEXT_PUBLIC_ADDRESS: "24 avenue des Vosges"
          NEXT_PUBLIC_POSTAL_CODE: "67000"
          NEXT_PUBLIC_CITY: "Strasbourg"
          NEXT_PUBLIC_LAWYER_NAME: "Test Lawyer"
          NEXT_PUBLIC_BAR: "Barreau de Strasbourg"
          NEXT_PUBLIC_SIRET: "12345678900000"
          NEXT_PUBLIC_CALENDLY_URL: "https://calendly.com/test"

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
